on:
  pull_request:
    paths:
      - src/*
      - .github/*

  push:
    branches:
      - test

name: Check if GitHub Actions works properly

jobs:
  check:
    name: Check action
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Slack Notification
        uses: homoluctus/slatify@feature/cancel
        if: always()
        with:
          # type: ${{ job.status }}
          type: cancel
          job_name: ':robot_face: *Check action*'
          channel: '#develop'
          url: ${{ secrets.SLACK_WEBHOOK }}